### ISSUE TITLE
File uploads on Windows differing from behavior on Unix due to JRuby File.open()

### ISSUE THREAD

**Issue by thomas-** [haplo-org/haplo-plugin-tool#2]
I reported this issue on the JRuby project:

https://github.com/jruby/jruby/issues/5100

But in short, 0x0D is being converted to 0x0A when reading the contents of files using File.open() without the binary flag

Obviously this doesn't much affect code upload, but I noticed when some gifs in `static/` started looking very broken after upload (and the resultant file hash being different...)

As a quick workaround I'm currently using "rb" in the plugin tools File.open()'s where it seems to be causing some problems (see commit: https://github.com/thomas-/haplo-plugin-tool/commit/8ff1f0b18aed88c0480afd0ba1d6e5403ad60ce0)

Appreciate this may be a wontfix, but figured it was worth reporting anyhow!

**Comment by bensummers** [comment]
Sorry to miss this issue, for some reason, notifications aren't happening.

A PR from your change would be gratefully merged. Not all files are text -- and even if they are, we don't want to change line endings.

**Comment by thomas-** [comment]
No worries! Submitted PR.
